
Runner.namespace('Runner.resize');Runner.resize.Grid=Runner.extend(Runner.emptyFn,{pageId:-1,gridSettings:null,columnObjs:null,columnNames:null,firstTime:false,isShowRows:false,isUseInlineAdd:false,isShowAddInPopup:false,constructor:function(cfg){Runner.apply(this,cfg);this.gridSettings={};this.pageObj=Runner.pages.PageManager.getAt(this.tName,this.pageId);this.firstTime=Runner.pages.PageSettings.getTableData(this.tName,"pageMode")!=Runner.pages.constants.LIST_AJAX;this.isShowRows=Runner.pages.PageSettings.getTableData(this.tName,"showRows");this.isUseInlineAdd=Runner.pages.PageSettings.getTableData(this.tName,"isInlineAdd");this.isShowAddInPopup=Runner.pages.PageSettings.getTableData(this.tName,"showAddInPopup");},init:function(){if(!this.isUseInlineAdd&&!this.isShowRows){return false;}
if(!$(document.body).hasClass('yui-skin-sam')){$(document.body).addClass('yui-skin-sam');}
this.gridSettings.classes={table:this.pageObj.gridElem[0].className};this.gridSettings.styles={table:this.pageObj.gridElem.attr('style')||''};this.parseGridHeader();this.parseGridBodyFoot();this.createResizeGrid();this.setOldGridSettings();},hasColRowSpans:function(cell){if(cell.colspan||cell.rowspan){return true;}
return false;},parseGridHeader:function(){var self=this,initCookies=new Array();this.columnObjs=[];this.columnNames=[];this.gridSettings.ieconts={ths:[]};this.gridSettings.classes.thead={trs:[],ths:[]};this.gridSettings.styles.thead={trs:[],ths:[]};$('thead tr',this.pageObj.gridElem).each(function(i){var columnId=0;self.gridSettings.classes.thead.trs[i]=this.className;self.gridSettings.styles.thead.trs[i]=$(this).attr('style')||'';$("th",this).each(function(){if(self.hasColRowSpans(this)){return;}
if($(this).hasClass("runner-cc")){self.columnNames[columnId]="column"+columnId;self.columnObjs[columnId]={key:self.columnNames[columnId],label:$(this).html(),resizeable:true,sortable:false};var gridCookie=YAHOO.util.Cookie.get(self.pageObj.shortTName);if(!gridCookie){self.columnObjs[columnId].width=this.offsetWidth;initCookies[initCookies.length]=self.columnObjs[columnId].width;}else{self.columnObjs[columnId].width=YAHOO.lang.JSON.parse(gridCookie)[columnId];}
self.gridSettings.ieconts.ths[columnId]=$(this).attr('ieditcont')!=undefined||"";self.gridSettings.classes.thead.ths[columnId]=this.className;self.gridSettings.styles.thead.ths[columnId]=$(this).attr('style')||'';columnId++;}});});if(!YAHOO.util.Cookie.get(this.pageObj.shortTName)){YAHOO.util.Cookie.set(this.pageObj.shortTName,YAHOO.lang.JSON.stringify(initCookies));}},parseGridBodyFoot:function(){var self=this,areaCodes=[],numColumns=0;this.gridSettings.rowids=[];this.gridSettings.ieconts.tds=[];this.gridSettings.classes.tbody={trs:[],tds:[]};this.gridSettings.styles.tbody={trs:[]};$("tbody .runner-row",this.pageObj.gridElem).each(function(i){self.gridSettings.classes.tbody.trs[i]=this.className;self.gridSettings.styles.tbody.trs[i]={tr:$(this).attr('style')||'',tds:[]};self.gridSettings.rowids[i]=this.id;var areaCode={},columnId=0,parseColumn=false;if(self.isShowRows&&(self.isUseInlineAdd&&i==1||!self.isUseInlineAdd&&!i)||!self.isShowRows&&self.isUseInlineAdd&&!i){parseColumn=true;}
$('td.runner-cc',this).each(function(j){if(self.hasColRowSpans(this)){return;}
areaCode[self.columnObjs[columnId].key]=$(this).html();self.gridSettings.styles.tbody.trs[i].tds[columnId]=$(this).attr('style')||'';if(parseColumn){self.gridSettings.classes.tbody.tds[columnId]=this.className;self.gridSettings.ieconts.tds[columnId]=$(this).attr('ieditcont')||'';}
columnId++;numColumns++;});areaCodes[areaCodes.length]=areaCode;});YAHOO.example.Data={areacodes:areaCodes};YAHOO.numCell=numColumns-1;},createResizeGrid:function(){var self=this;YAHOO.firstTime=this.firstTime;YAHOO.example.MultipleFeatures=function(){var myDataSource=new YAHOO.util.DataSource(YAHOO.example.Data.areacodes);myDataSource.responseType=YAHOO.util.DataSource.TYPE_JSARRAY;myDataSource.responseSchema={fields:self.columnNames};YAHOO.myDataSource=myDataSource;var myDataTable=new YAHOO.widget.DataTable(self.pageObj.gridElem.parent()[0],self.columnObjs,YAHOO.myDataSource,{draggableColumns:false},YAHOO.firstTime);myDataTable.addListener("columnResizeEvent",function(params){var value=new String(params["column"]),num=parseInt(value.substr(23)),gridCookie=YAHOO.lang.JSON.parse(YAHOO.util.Cookie.get(self.pageObj.shortTName)),updateCookie=new Array(),len=gridCookie.length;if(!YAHOO.firstTime){num=num-len*(YAHOO.widget.DataTable._nCount-1);}
for(var i=0;i<len;i++){if(i==num){gridCookie[i]=params["width"];}
updateCookie[i]=gridCookie[i];}
YAHOO.util.Cookie.set(self.pageObj.shortTName,YAHOO.lang.JSON.stringify(updateCookie));});return{oDS:myDataSource,oDT:myDataTable};}();},setOldGridSettings:function(){var self=this;var newGridElem=$('.runner-s-grid table',this.pageObj.pageCont).not(function(){if($(this).closest('.runner-b-masterinfo').length)
return true;});if(!this.isShowRows){$(newGridElem).hide();}
newGridElem.addClass(this.gridSettings.classes.table);if(this.gridSettings.styles.table){newGridElem.attr('style',this.gridSettings.styles.table);}
$('thead tr',newGridElem).each(function(i){$(this).addClass(self.gridSettings.classes.thead.trs[i]);if(self.gridSettings.styles.thead.trs[i]){$(this).attr('style',self.gridSettings.styles.thead.trs[i]);}
$('th',this).each(function(j){$(this).addClass(self.gridSettings.classes.thead.ths[j]);if(self.gridSettings.styles.thead.ths[j]){$(this).attr('style',self.gridSettings.styles.thead.ths[j]);}
if(self.gridSettings.ieconts[j]){$(this).attr('ieditcont')=self.gridSettings.ieconts.ths[j];}});});$('tbody.yui-dt-data tr',newGridElem).each(function(i){$(this).addClass(self.gridSettings.classes.tbody.trs[i]);var isRowTFoot=false;if($(this).hasClass('footer')){isRowTFoot=true;}
this.id=self.gridSettings.rowids[i];if(!isRowTFoot&&self.gridSettings.styles.tbody.trs[i].tr){$(this).attr('style',self.gridSettings.styles.tbody.trs[i].tr);}
$('td',this).each(function(j){$(this).addClass(self.gridSettings.classes.tbody.tds[j]);if(!isRowTFoot){if(self.gridSettings.styles.tbody.trs[i].tds[j]){$(this).attr('style',self.gridSettings.styles.tbody.trs[i].tds[j]);}
if(self.gridSettings.ieconts[j]){$(this).attr('ieditcont')=self.gridSettings.ieconts.tds[j];}}});});}});